version: "3.9"

services:
  db:
    image: postgres:16
    container_name: piscines_db
    environment:
      POSTGRES_DB: piscines
      POSTGRES_USER: piscines
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U piscines"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: piscines_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: ./backend
    container_name: piscines_web
    entrypoint: ["/app/entrypoint.sh"]
    command: gunicorn config.wsgi:application -b 0.0.0.0:8000 --workers 3 --timeout 120
    environment:
      DJANGO_DEBUG: "false"
      SECRET_KEY: change-me-in-prod
      ALLOWED_HOSTS: "*"
      CORS_ALLOWED_ORIGINS: "http://localhost:5173"
      CSRF_TRUSTED_ORIGINS: "http://localhost:5173"
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: piscines
      DB_USER: piscines
      DB_PASSWORD: changeme
      DB_HOST: db
      DB_PORT: "5432"
      REDIS_URL: redis://redis:6379/0
      FRONTEND_ORIGIN: http://localhost:5173
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      DJANGO_SETTINGS_MODULE: config.settings
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"

  worker:
    build: ./backend
    container_name: piscines_worker
    entrypoint: ["/app/entrypoint.sh"]
    command: celery -A config worker -l info --concurrency=2
    environment:
      DJANGO_DEBUG: "false"
      SECRET_KEY: change-me-in-prod
      ALLOWED_HOSTS: "*"
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: piscines
      DB_USER: piscines
      DB_PASSWORD: changeme
      DB_HOST: db
      DB_PORT: "5432"
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      DJANGO_SETTINGS_MODULE: config.settings
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  beat:
    build: ./backend
    container_name: piscines_beat
    entrypoint: ["/app/entrypoint.sh"]
    command: celery -A config beat -l info
    environment:
      DJANGO_DEBUG: "false"
      SECRET_KEY: change-me-in-prod
      ALLOWED_HOSTS: "*"
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: piscines
      DB_USER: piscines
      DB_PASSWORD: changeme
      DB_HOST: db
      DB_PORT: "5432"
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      DJANGO_SETTINGS_MODULE: config.settings
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  dbdata:
